/**
 * Brand resolution for the MCP server.
 *
 * The extension is white-labelled by `scripts/brand-build.mjs` from
 * `brand/brand.config.json`; this server is branded from the same file so a
 * branch only ever differs in config, never in code. Everything user-visible —
 * server name, tool names, product name in messages, env-var prefix, skill and
 * bundle file names — derives from here.
 *
 * Optional overrides live under an `mcp` key in brand.config.json:
 *   { "mcp": { "serverName": "netmind", "toolPrefix": "netmind",
 *              "envPrefix": "NETMIND_", "skillName": "netmind",
 *              "packageName": "netmind-mcp" } }
 * Anything omitted is derived from `product`.
 */

import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const repoRoot = resolve(packageDir, "..");

const ident = (value) =>
  String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");

/** Pure: brand.config.json contents → the brand record the server compiles in. */
export function deriveBrand(config) {
  const product = config?.product || {};
  const mcp = config?.mcp || {};
  const shortName = product.shortName || product.name || "WebMate";
  const slug = product.slug || ident(product.name || shortName).replace(/_/g, "-");
  const toolPrefix = ident(mcp.toolPrefix || shortName);
  if (!toolPrefix) throw new Error("brand: cannot derive a tool prefix from product.shortName");
  const serverName = mcp.serverName || slug;
  const productName = product.name || shortName;
  return {
    productName,
    // "the AgentX WebMate extension" but "the netMind Extension" — never "Extension extension".
    extensionName: /\bextension$/i.test(productName) ? productName : `${productName} extension`,
    shortName,
    slug,
    homepage: product.homepage || "",
    serverName,
    toolPrefix,
    envPrefix: mcp.envPrefix || `${toolPrefix.toUpperCase()}_`,
    skillName: mcp.skillName || toolPrefix,
    packageName: mcp.packageName || `${slug}-mcp`,
    bundleFile: `${serverName}-mcp.mjs`,
  };
}

export function loadBrandConfig(root = repoRoot) {
  return JSON.parse(readFileSync(join(root, "brand", "brand.config.json"), "utf8"));
}

export function loadBrand(root = repoRoot) {
  return deriveBrand(loadBrandConfig(root));
}

/** TypeScript source for src/brand.generated.ts. */
export function renderBrandModule(brand) {
  return (
    "// GENERATED by scripts/gen-brand.mjs from brand/brand.config.json — do not edit, do not commit.\n" +
    `export const BRAND = ${JSON.stringify(brand, null, 2)} as const;\n\n` +
    "/** Tool name under this brand, e.g. tool('run') → 'webmate_run'. */\n" +
    "export const tool = (name: string): string => `${BRAND.toolPrefix}_${name}`;\n\n" +
    "/** Fully namespaced name as MCP hosts show it: hosts prefix with the key the server was registered under (skillName), not with the server's self-reported name. */\n" +
    "export const hostTool = (name: string): string => `mcp__${BRAND.skillName}__${tool(name)}`;\n"
  );
}
